### ISSUE TITLE
Write javadoc for method signatures for StackOfBooks

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabB-Team1#5]
Write javadoc for method signatures for StackOfBooks

**Comment by alternatebow** [comment]
I don't know if anyones see the user line comments, but I decided to just use the alternate methods you suggested Karl. It should be reflected on the merge request.

**Comment by karlnicholas** [comment]
Hi Calvin, 
I'm not sure what you mean by "user line comments". I've picked up the merge and Jill's updates and the interface seems to be in pretty good shape from what I can tell. I'm going to close these two issues we'll move to sign-off.

**Comment by karlnicholas** [comment]
Three warnings from Java 8 javadoc generator:

Generating C:\Users\quix0\workspace\LabB-Team1\doc\StackOfBooks.html...
C:\Users\quix0\workspace\LabB-Team1\src\StackOfBooks.java:55: warning: no @param for item
    public E peek(E item);
             ^
C:\Users\quix0\workspace\LabB-Team1\src\StackOfBooks.java:63: warning: no @param for item
    public E pop(E item);
             ^
C:\Users\quix0\workspace\LabB-Team1\src\StackOfBooks.java:77: warning: no description for @param
     * @param item
       ^
Generating C:\Users\quix0\workspace\LabB-Team1\doc\package-frame.html...

**Comment by alternatebow** [comment]
Should the peek method have a parameter to begin with? I mean it only returns whatever is first on the stack.

**Comment by karlnicholas** [comment]
No indeed. Neither peek or pop should have parameters. Good catch. I've reopened issue #4.

**Comment by jillHuang7** [comment]
i think both peek and pop no need para. As the pop removes the object at the top of this stack, and peek looks at the object at the top of this stack without removing it from the stack. I hope it might be right.

**Comment by karlnicholas** [comment]
I came to the same conclusion. Don’t be afraid to leave your comments in the issue even if they are the same as others. It shows your work and your understanding.

**Comment by alternatebow** [comment]
Ok, so i took a look at the ec part of the lab. Looks like we made the necessary changes. Are we clear to close this issue?

**Comment by karlnicholas** [comment]
I changed the search parameter back to E item. Object is not correct because the class uses generics. Object is only appropriate when you are overloading a method in a superclass that uses Object. 

All looks good now, closing and moving to signoff.
