### ISSUE TITLE
Submit zipped files to insight.

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabB-Team1#7]

**Comment by alternatebow** [comment]
So who's doing the honors?

**Comment by karlnicholas** [comment]
Looks like we have a volunteer. :)

Sent from my iPhone

On Sep 9, 2016, at 5:35 PM, alternatebow <notifications@github.com> wrote:

So who's doing the honors?

**Comment by alternatebow** [comment]
Ahh... Not cool. Alright I'll submit it tmr.

**Comment by karlnicholas** [comment]
Sounds good, thanks!

Sent from my iPhone

On Sep 9, 2016, at 7:18 PM, alternatebow <notifications@github.com> wrote:

Ahh... Not cool. Alright I'll submit it tmr.

**Comment by alternatebow** [comment]
Just letting everyone know I submitted the lab.

**Comment by jillHuang7** [comment]
Thank you guys! I really learned a lot from this Lab with you. Not only the code but also how GitHub works!  I appreciated it! :)
